# Generated by Django 6.0 on 2025-12-23 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="image_url",
            field=models.CharField(
                blank=True,
                help_text="URL or path (e.g., /static/images/products/widget.jpg)",
                max_length=500,
            ),
        ),
    ]
